"""Establish the frozen TraceHawk v0.7.1 persistence schema.

Revision ID: 0001_current_schema
Revises: None
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "0001_current_schema"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "analysis_runs",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("source_id", sa.String(length=255), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("parser", sa.String(length=80), nullable=False),
        sa.Column("raw_line_count", sa.Integer(), nullable=False),
        sa.Column("parsed_event_count", sa.Integer(), nullable=False),
        sa.Column("finding_count", sa.Integer(), nullable=False),
        sa.Column("incident_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_analysis_runs_created_at"), "analysis_runs", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_analysis_runs_source_id"), "analysis_runs", ["source_id"], unique=False
    )
    op.create_table(
        "app_settings",
        sa.Column("key", sa.String(length=120), nullable=False),
        sa.Column("value", sa.JSON(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "audit_events",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actor", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("role", sa.String(length=40), nullable=False),
        sa.Column("auth_mode", sa.String(length=40), nullable=False),
        sa.Column("method", sa.String(length=16), nullable=False),
        sa.Column("path", sa.String(length=512), nullable=False),
        sa.Column("action", sa.String(length=600), nullable=False),
        sa.Column("status_code", sa.Integer(), nullable=False),
        sa.Column("outcome", sa.String(length=40), nullable=False),
        sa.Column("request_id", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_events_actor"), "audit_events", ["actor"], unique=False)
    op.create_index(op.f("ix_audit_events_email"), "audit_events", ["email"], unique=False)
    op.create_index(
        op.f("ix_audit_events_occurred_at"), "audit_events", ["occurred_at"], unique=False
    )
    op.create_index(op.f("ix_audit_events_outcome"), "audit_events", ["outcome"], unique=False)
    op.create_index(op.f("ix_audit_events_path"), "audit_events", ["path"], unique=False)
    op.create_index(
        op.f("ix_audit_events_request_id"), "audit_events", ["request_id"], unique=False
    )
    op.create_index(op.f("ix_audit_events_role"), "audit_events", ["role"], unique=False)
    op.create_index(
        op.f("ix_audit_events_status_code"), "audit_events", ["status_code"], unique=False
    )
    op.create_table(
        "analyst_notes",
        sa.Column("id", sa.String(length=512), nullable=False),
        sa.Column("analysis_id", sa.String(length=64), nullable=False),
        sa.Column("incident_id", sa.String(length=512), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("note_type", sa.String(length=40), nullable=False),
        sa.Column("author", sa.String(length=120), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["analysis_id"],
            ["analysis_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_analyst_notes_analysis_id"), "analyst_notes", ["analysis_id"], unique=False
    )
    op.create_index(
        op.f("ix_analyst_notes_created_at"), "analyst_notes", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_analyst_notes_incident_id"), "analyst_notes", ["incident_id"], unique=False
    )
    op.create_index(
        op.f("ix_analyst_notes_note_type"), "analyst_notes", ["note_type"], unique=False
    )
    op.create_index(
        op.f("ix_analyst_notes_updated_at"), "analyst_notes", ["updated_at"], unique=False
    )
    op.create_table(
        "entities",
        sa.Column("id", sa.String(length=512), nullable=False),
        sa.Column("analysis_id", sa.String(length=64), nullable=False),
        sa.Column("entity_type", sa.String(length=40), nullable=False),
        sa.Column("value", sa.String(length=512), nullable=False),
        sa.Column("first_seen", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_seen", sa.DateTime(timezone=True), nullable=True),
        sa.Column("risk_score", sa.Integer(), nullable=False),
        sa.Column("event_count", sa.Integer(), nullable=False),
        sa.Column("source_ids", sa.JSON(), nullable=False),
        sa.Column("finding_ids", sa.JSON(), nullable=False),
        sa.Column("incident_ids", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["analysis_id"],
            ["analysis_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_entities_analysis_id"), "entities", ["analysis_id"], unique=False)
    op.create_index(op.f("ix_entities_entity_type"), "entities", ["entity_type"], unique=False)
    op.create_index(op.f("ix_entities_risk_score"), "entities", ["risk_score"], unique=False)
    op.create_index(op.f("ix_entities_value"), "entities", ["value"], unique=False)
    op.create_table(
        "findings",
        sa.Column("id", sa.String(length=512), nullable=False),
        sa.Column("analysis_id", sa.String(length=64), nullable=False),
        sa.Column("rule_id", sa.String(length=255), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("severity", sa.String(length=40), nullable=False),
        sa.Column("confidence", sa.String(length=40), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("mitre", sa.JSON(), nullable=False),
        sa.Column("first_seen", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen", sa.DateTime(timezone=True), nullable=False),
        sa.Column("event_count", sa.Integer(), nullable=False),
        sa.Column("evidence_line_ids", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["analysis_id"],
            ["analysis_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_findings_analysis_id"), "findings", ["analysis_id"], unique=False)
    op.create_index(op.f("ix_findings_first_seen"), "findings", ["first_seen"], unique=False)
    op.create_index(op.f("ix_findings_last_seen"), "findings", ["last_seen"], unique=False)
    op.create_index(op.f("ix_findings_rule_id"), "findings", ["rule_id"], unique=False)
    op.create_index(op.f("ix_findings_severity"), "findings", ["severity"], unique=False)
    op.create_table(
        "incidents",
        sa.Column("id", sa.String(length=512), nullable=False),
        sa.Column("analysis_id", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("severity", sa.String(length=40), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("first_seen", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen", sa.DateTime(timezone=True), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("finding_ids", sa.JSON(), nullable=False),
        sa.Column("entities", sa.JSON(), nullable=False),
        sa.Column("timeline", sa.JSON(), nullable=False),
        sa.Column("mitre_techniques", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["analysis_id"],
            ["analysis_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_incidents_analysis_id"), "incidents", ["analysis_id"], unique=False)
    op.create_index(op.f("ix_incidents_first_seen"), "incidents", ["first_seen"], unique=False)
    op.create_index(op.f("ix_incidents_last_seen"), "incidents", ["last_seen"], unique=False)
    op.create_index(op.f("ix_incidents_score"), "incidents", ["score"], unique=False)
    op.create_index(op.f("ix_incidents_severity"), "incidents", ["severity"], unique=False)
    op.create_index(op.f("ix_incidents_status"), "incidents", ["status"], unique=False)
    op.create_table(
        "log_sources",
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column("analysis_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("source_type", sa.String(length=40), nullable=False),
        sa.Column("parser_type", sa.String(length=80), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["analysis_id"],
            ["analysis_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_log_sources_analysis_id"), "log_sources", ["analysis_id"], unique=False
    )
    op.create_table(
        "parsed_events",
        sa.Column("id", sa.String(length=512), nullable=False),
        sa.Column("analysis_id", sa.String(length=64), nullable=False),
        sa.Column("source_id", sa.String(length=255), nullable=False),
        sa.Column("raw_line_id", sa.String(length=512), nullable=False),
        sa.Column("event_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("event_type", sa.String(length=120), nullable=False),
        sa.Column("host", sa.String(length=255), nullable=True),
        sa.Column("service", sa.String(length=120), nullable=True),
        sa.Column("source_ip", sa.String(length=80), nullable=True),
        sa.Column("username", sa.String(length=255), nullable=True),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("normalized_fields", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["analysis_id"],
            ["analysis_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_parsed_events_analysis_id"), "parsed_events", ["analysis_id"], unique=False
    )
    op.create_index(
        op.f("ix_parsed_events_event_type"), "parsed_events", ["event_type"], unique=False
    )
    op.create_index(
        op.f("ix_parsed_events_raw_line_id"), "parsed_events", ["raw_line_id"], unique=False
    )
    op.create_index(
        op.f("ix_parsed_events_source_id"), "parsed_events", ["source_id"], unique=False
    )
    op.create_index(
        op.f("ix_parsed_events_source_ip"), "parsed_events", ["source_ip"], unique=False
    )
    op.create_index(op.f("ix_parsed_events_username"), "parsed_events", ["username"], unique=False)
    op.create_table(
        "raw_log_lines",
        sa.Column("id", sa.String(length=512), nullable=False),
        sa.Column("analysis_id", sa.String(length=64), nullable=False),
        sa.Column("source_id", sa.String(length=255), nullable=False),
        sa.Column("line_number", sa.Integer(), nullable=False),
        sa.Column("raw_text", sa.Text(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("timestamp_observed", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["analysis_id"],
            ["analysis_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_raw_log_lines_analysis_id"), "raw_log_lines", ["analysis_id"], unique=False
    )
    op.create_index(
        op.f("ix_raw_log_lines_content_hash"), "raw_log_lines", ["content_hash"], unique=False
    )
    op.create_index(
        op.f("ix_raw_log_lines_source_id"), "raw_log_lines", ["source_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_raw_log_lines_source_id"), table_name="raw_log_lines")
    op.drop_index(op.f("ix_raw_log_lines_content_hash"), table_name="raw_log_lines")
    op.drop_index(op.f("ix_raw_log_lines_analysis_id"), table_name="raw_log_lines")
    op.drop_table("raw_log_lines")
    op.drop_index(op.f("ix_parsed_events_username"), table_name="parsed_events")
    op.drop_index(op.f("ix_parsed_events_source_ip"), table_name="parsed_events")
    op.drop_index(op.f("ix_parsed_events_source_id"), table_name="parsed_events")
    op.drop_index(op.f("ix_parsed_events_raw_line_id"), table_name="parsed_events")
    op.drop_index(op.f("ix_parsed_events_event_type"), table_name="parsed_events")
    op.drop_index(op.f("ix_parsed_events_analysis_id"), table_name="parsed_events")
    op.drop_table("parsed_events")
    op.drop_index(op.f("ix_log_sources_analysis_id"), table_name="log_sources")
    op.drop_table("log_sources")
    op.drop_index(op.f("ix_incidents_status"), table_name="incidents")
    op.drop_index(op.f("ix_incidents_severity"), table_name="incidents")
    op.drop_index(op.f("ix_incidents_score"), table_name="incidents")
    op.drop_index(op.f("ix_incidents_last_seen"), table_name="incidents")
    op.drop_index(op.f("ix_incidents_first_seen"), table_name="incidents")
    op.drop_index(op.f("ix_incidents_analysis_id"), table_name="incidents")
    op.drop_table("incidents")
    op.drop_index(op.f("ix_findings_severity"), table_name="findings")
    op.drop_index(op.f("ix_findings_rule_id"), table_name="findings")
    op.drop_index(op.f("ix_findings_last_seen"), table_name="findings")
    op.drop_index(op.f("ix_findings_first_seen"), table_name="findings")
    op.drop_index(op.f("ix_findings_analysis_id"), table_name="findings")
    op.drop_table("findings")
    op.drop_index(op.f("ix_entities_value"), table_name="entities")
    op.drop_index(op.f("ix_entities_risk_score"), table_name="entities")
    op.drop_index(op.f("ix_entities_entity_type"), table_name="entities")
    op.drop_index(op.f("ix_entities_analysis_id"), table_name="entities")
    op.drop_table("entities")
    op.drop_index(op.f("ix_analyst_notes_updated_at"), table_name="analyst_notes")
    op.drop_index(op.f("ix_analyst_notes_note_type"), table_name="analyst_notes")
    op.drop_index(op.f("ix_analyst_notes_incident_id"), table_name="analyst_notes")
    op.drop_index(op.f("ix_analyst_notes_created_at"), table_name="analyst_notes")
    op.drop_index(op.f("ix_analyst_notes_analysis_id"), table_name="analyst_notes")
    op.drop_table("analyst_notes")
    op.drop_index(op.f("ix_audit_events_status_code"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_role"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_request_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_path"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_outcome"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_occurred_at"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_email"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_actor"), table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_table("app_settings")
    op.drop_index(op.f("ix_analysis_runs_source_id"), table_name="analysis_runs")
    op.drop_index(op.f("ix_analysis_runs_created_at"), table_name="analysis_runs")
    op.drop_table("analysis_runs")
    # ### end Alembic commands ###
