#!/usr/bin/env python3
"""Generate deterministic OpenAPI and TypeScript contract artifacts.

The generator intentionally has no JavaScript code-generation dependency. The
FastAPI application remains the sole source of truth, while CI can prove that
the checked-in browser contract was generated from the current backend models.
"""

from __future__ import annotations

import argparse
import difflib
import json
import re
import sys
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
API_ROOT = ROOT / "apps" / "api"
OPENAPI_PATH = ROOT / "apps" / "web" / "src" / "generated" / "openapi.json"
TYPESCRIPT_PATH = ROOT / "apps" / "web" / "src" / "generated" / "api-schema.ts"
REFERENCE_PREFIX = "#/components/schemas/"
IDENTIFIER_PATTERN = re.compile(r"^[A-Za-z_$][A-Za-z0-9_$]*$")


def _openapi_document() -> dict[str, Any]:
    sys.path.insert(0, str(API_ROOT))
    from tracehawk_api.main import app  # noqa: PLC0415

    return app.openapi()


def _json_literal(value: Any) -> str:
    if value is None:
        return "null"
    if value is True:
        return "true"
    if value is False:
        return "false"
    return json.dumps(value, ensure_ascii=False)


def _property_name(name: str) -> str:
    return name if IDENTIFIER_PATTERN.fullmatch(name) else json.dumps(name)


def _indent_multiline(value: str, indentation: str) -> str:
    return value.replace("\n", f"\n{indentation}")


def _render_object(schema: dict[str, Any], level: int) -> str:
    properties = schema.get("properties", {})
    required = set(schema.get("required", []))
    indent = "  " * level
    child_indent = "  " * (level + 1)
    lines = ["{"]
    for name in sorted(properties):
        optional = "" if name in required else "?"
        rendered = _indent_multiline(_render_schema(properties[name], level + 1), child_indent)
        lines.append(f"{child_indent}{_property_name(name)}{optional}: {rendered};")

    additional = schema.get("additionalProperties")
    if additional is True:
        lines.append(f"{child_indent}[key: string]: unknown;")
    elif isinstance(additional, dict):
        rendered = _indent_multiline(_render_schema(additional, level + 1), child_indent)
        lines.append(f"{child_indent}[key: string]: {rendered};")

    lines.append(f"{indent}}}")
    return "\n".join(lines)


def _render_schema(schema: dict[str, Any], level: int = 0) -> str:
    reference = schema.get("$ref")
    if reference:
        if not reference.startswith(REFERENCE_PREFIX):
            raise ValueError(f"Unsupported OpenAPI reference: {reference}")
        return reference.removeprefix(REFERENCE_PREFIX)

    for union_key in ("anyOf", "oneOf"):
        if union_key in schema:
            return " | ".join(_render_schema(item, level) for item in schema[union_key])

    if "allOf" in schema:
        return " & ".join(_render_schema(item, level) for item in schema["allOf"])

    if "const" in schema:
        return _json_literal(schema["const"])

    enum = schema.get("enum")
    if enum is not None:
        return " | ".join(_json_literal(item) for item in enum) or "never"

    schema_type = schema.get("type")
    if isinstance(schema_type, list):
        return " | ".join(_render_schema({"type": item}, level) for item in schema_type)
    if schema_type == "string":
        return "string"
    if schema_type in {"integer", "number"}:
        return "number"
    if schema_type == "boolean":
        return "boolean"
    if schema_type == "null":
        return "null"
    if schema_type == "array":
        item_type = _render_schema(schema.get("items", {}), level)
        if " | " in item_type or " & " in item_type:
            item_type = f"({item_type})"
        return f"{item_type}[]"
    if schema_type == "object" or "properties" in schema or "additionalProperties" in schema:
        if not schema.get("properties") and isinstance(schema.get("additionalProperties"), dict):
            return f"Record<string, {_render_schema(schema['additionalProperties'], level)}>"
        if not schema.get("properties") and schema.get("additionalProperties") is True:
            return "Record<string, unknown>"
        return _render_object(schema, level)

    return "unknown"


def _typescript_contract(document: dict[str, Any]) -> str:
    schemas = document.get("components", {}).get("schemas", {})
    if not schemas:
        raise ValueError("OpenAPI document has no component schemas")

    lines = [
        "/* eslint-disable */",
        "/**",
        " * Generated by tools/generate_api_contract.py from the FastAPI OpenAPI schema.",
        " * Do not edit this file by hand; run `make api-contract`.",
        " */",
        "",
    ]
    for name in sorted(schemas):
        rendered = _render_schema(schemas[name])
        lines.append(f"export type {name} = {rendered};")
        lines.append("")

    lines.extend(
        [
            "export interface ApiSchemas {",
            *[f"  {name}: {name};" for name in sorted(schemas)],
            "}",
            "",
        ]
    )
    return "\n".join(lines)


def generated_contract() -> dict[Path, str]:
    document = _openapi_document()
    return {
        OPENAPI_PATH: json.dumps(document, indent=2, sort_keys=True, ensure_ascii=False) + "\n",
        TYPESCRIPT_PATH: _typescript_contract(document),
    }


def _diff(path: Path, expected: str) -> str:
    actual = path.read_text(encoding="utf-8") if path.exists() else ""
    return "".join(
        difflib.unified_diff(
            actual.splitlines(keepends=True),
            expected.splitlines(keepends=True),
            fromfile=str(path.relative_to(ROOT)),
            tofile=f"generated:{path.relative_to(ROOT)}",
        )
    )


def check_contract() -> list[str]:
    return [difference for path, expected in generated_contract().items() if (difference := _diff(path, expected))]


def write_contract() -> None:
    for path, content in generated_contract().items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        print(f"wrote {path.relative_to(ROOT)}")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if checked-in artifacts differ")
    args = parser.parse_args()

    if not args.check:
        write_contract()
        return 0

    differences = check_contract()
    if not differences:
        print("API contract artifacts are current")
        return 0
    print("API contract drift detected; run `make api-contract`", file=sys.stderr)
    for difference in differences:
        print(difference, file=sys.stderr)
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
